### ISSUE TITLE
document where to find logs and what to provide in bug report

### ISSUE THREAD

**Issue by kparal** [rpm-software-management/dnf-plugin-system-upgrade#11]
Please document in the README where to look for logs for failed upgrade runs, and what to attach to bug reports. You'll make your life easier when people report problems, and you'll make our life easier when trying to find out where all the important pieces are stored. Thanks.

Also, please consider creating a separate `system-upgrade.log`. It would make debugging and bug reporting so much easier.

**Comment by keszybz** [comment]
The first thing would be to decide what to recommend:
- `journalctl -b-1` is probably the best option for debugging failed upgrades
- `rpm -qa` is useful for when the download fails
- Rerunning with `--debugsolver` will probably give the best information

Anything else?

**Comment by kparal** [comment]
If people rebooted multiple times since the upgrade process and then want to report a bug, is there a good way to find which journal boot number contains the actual upgrade? I know we can advice them to use `journalctl --list-boots` and try to remember the date and time, but is there something better? Perhaps a unique string during the early upgrade process we can search for and then somehow learn the relevant boot number?

The easiest approach from user POV would be if we could create `/var/log/upgrade/download.log` and `/var/log/upgrade/upgrade.log` and then just point them to there.

We could also collect `rpm -qa` and `--debugsolver` automatically at the same time to the same dir, but that's up to consideration. If we don't, having that at least among suggestions for bug reports is a great idea, thanks @keszybz.

**Comment by keszybz** [comment]
> Perhaps a unique string during the early upgrade process

Better than a unique string would be a custom message id (http://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#MESSAGE_ID=).

> create /var/log/upgrade/download.log and /var/log/upgrade/upgrade.log

I think that download.log would be fairly easy to generate by adding a new logger output. On the other hand upgrade.log would be harder, because you basically want the equivalent of 'journalctl -b' for that boot, from before the time that dnf starts the upgrade until the reboot. So emitting a MESSAGE_ID tagged line to identity the upgrade and then taking the full 'journalctl -b' for that boot would be the best imo. With the python wrappers for the journal, we could have a wrapper which would do that in a few lines of code.

**Comment by wgwoods** [comment]
> > Perhaps a unique string during the early upgrade process
> 
> Better than a unique string would be a custom message id
> (http://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#MESSAGE_ID=).

I had been toying with stashing the boot id in `/var/lib/dnf/system-upgrade.state`, so the user could do something like:

```
dnf system-upgrade log [list|BOOTID]
```

..which would call `journalctl` to show the log from the last upgrade boot (or previous upgrade, if you did `log -1`. But I like the custom message ID better. We could send a message with a custom message ID and some other metadata at the start of the upgrade, like, say:

```
MESSAGE_ID=$SYSTEM_UPGRADE_UUID
SYSTEM_RELEASEVER=22
TARGET_RELEASEVER=23
MESSAGE="Starting upgrade from Fedora 22 to Fedora 23"
```

> So emitting a MESSAGE_ID tagged line to identity the upgrade and then taking the full 'journalctl -b' for that boot would be the best imo.

So if I understand correctly, if the plugin was sending the above message I could later use the journal API to _find_ messages with that `MESSAGE_ID`, and they would each have a `_BOOT_ID` field which I could use to get the whole log for that boot. Is that right?

**Comment by wgwoods** [comment]
(on the other hand, I want to keep `dnf-plugin-system-upgrade`'s requirements minimal, so I'm not totally sure if it's better to require `systemd-python` or just dump `/proc/sys/kernel/random/boot_id` somewhere myself...)

**Comment by keszybz** [comment]
I don't think that python[3]-systemd dependency is a problem. dnf requires python[3] already, and systemd must be installed too, and python[3]-systemd itself is a tiny wrapper.

I whipped up a POC implementation that either prints a list of boots having a message with a specific message id, or dumps the logs for the specified boot in the sequence. When doing that, I realized that to show the logs properly, it is best to call out to journalctl (to have highlighting and other niceties). OTOH, it is nice to have the code to list boots in python. Using your sample line we could show something like this:

```
$ dnf system-upgrade log
The following upgrade attempts were found in the logs:
1: 2015-10-01 01:00:22 Starting upgrade from Fedora 22 to Fedora 23
2: 2015-12-01 02:00:22 Starting upgrade from Fedora 23 to Fedora 24
3: 2015-12-01 02:05:11 Starting upgrade from Fedora 23 to Fedora 24
Use "dnf system-upgrade log <n>" to show the log for a specific boot.
```

Then 'dnf system-upgrade log 3' and 'dnf system-upgrade log -1' would be equivalent.

``` python
from __future__ import print_function
import uuid
import argparse
import subprocess
from systemd import journal

def parser():
    p = argparse.ArgumentParser()
    p.add_argument('boot', nargs='?', type=int,
                   help='show this boot in sequence')
    p.add_argument('--id', type=uuid.UUID,
                   default=uuid.UUID('f77379a8490b408bbe5f6940505a777b'),
                   help='use this MESSAGE_ID')
    p.add_argument('--journalctl', '-j', action='store_true',
                   help='use jouralctl to show the boot')
    return p

def find_boots(message_id):
    """Find all boots with this message id.

    Returns the entries of all found boots.
    """
    j = journal.Reader()
    j.add_match(MESSAGE_ID=message_id.hex)

    oldboot = None
    for entry in j:
        boot = entry['_BOOT_ID']
        if boot == oldboot:
            continue
        oldboot = boot
        yield entry

def pick_boot(message_id, n):
    boots = list(find_boots(message_id))
    # Positive indices index all found boots starting with 1 and going forward,
    # zero is the current boot, and -1, -2, -3 are previous going backwards.
    # This is the same as journalctl.
    return boots[n - 1]['_BOOT_ID']

def dump_boot(boot_id):
    j = journal.Reader()
    j.this_boot(boot_id)
    entry = next(j)
    print(entry['__REALTIME_TIMESTAMP'].isoformat(), entry['MESSAGE'])
    print('...')
    j.seek_tail()
    entry = j.get_previous()
    print(entry['__REALTIME_TIMESTAMP'].isoformat(), entry['MESSAGE'])

def show_boot(boot_id):
    subprocess.check_call(['journalctl', '--boot', boot_id.hex])

def main(args):
    if args.boot is None:
        for n, entry in enumerate(find_boots(args.id)):
            print('{} / {}: {}'
                  .format(n + 1,
                          entry['_BOOT_ID'],
                          entry['__REALTIME_TIMESTAMP'].isoformat()))
    else:
        boot = pick_boot(args.id, args.boot)
        if args.journalctl:
            show_boot(boot)
        else:
            dump_boot(boot)

if __name__ == '__main__':
    args = parser().parse_args()
    main(args)
```

(This uses "Journal started" MESSAGE_ID as a placeholder. Works nice and fast on my system.)

The other option of stashing some state in /var/lib/dnf/systemd-upgrade.state could work too. But I'm not sure that it is really more lightweight, because some logic to list the boots would be required anyway, and it would necessary to check that the logs are still available for the specified entry, so things would be more complicated. The solution with journalctl integration and MESSAGE_ID matching is nice because there's no housekeeping or cleanup required of any sort.

If you like the approach from the POC above I would make this into a proper PR.

**Comment by wgwoods** [comment]
> I don't think that python[3]-systemd dependency is a problem. dnf requires python[3] already, and systemd must be installed too, and python[3]-systemd itself is a tiny wrapper.

Good point! If python-systemd itself doesn't pull in other external dependencies then I have no worries about it.

> The solution with journalctl integration and MESSAGE_ID matching is nice because there's no housekeeping or cleanup required of any sort.

Agreed - let the journal track the journal's state!

> If you like the approach from the POC above I would make this into a proper PR.

Please do! And thanks very much for your help!

**Comment by wgwoods** [comment]
Thanks to @keszybz we now have a `log` subcommand that will show you the upgrade logs - see #21 for details.
