### ISSUE TITLE
please create version for el7 and el8 on epel

### ISSUE THREAD

**Issue by amidevous** [rpm-software-management/dnf-plugin-system-upgrade#59]
please create version for el7 and el8 on epel

please it's a real mess to update

centos 7 to 8 or 8 to 9

with the conflicts

please create dnf-plugin-system-upgrade for this version

and publish it on epel please thank you

**Comment by pirat89** [comment]
@amidevous Hi, here is one of guys working on upgrades between elX systems. The system-upgrade plugin cannot handle upgrades between el7 & el8 - it's far away beyond current functionality. The plugin is doing great job when upgrading from one Fedora release to another, but el7 -> el8 jump is upgrade over 10 Fedora releases. That's why the leapp tooling exists for RHEL systems. To summarize couple of technical issues that blocks the use of the plugin:
* dnf & rpm on el7 does not understand boolean dependencies, so dnf & rpm from el8 must be used
* requried changed rpmdb format
* SPEC files for el7 & el8 do not contains all required information needed for the upgrade (as Fedora keeps spec files valid usually just for last 2 releases, so information aboust Obsoletes & Provides is missing in packages and dnf does not know what to do).

There are now basically two ways to do the upgrade:
* use the [Elevate tool](https://almalinux.org/elevate) which is fork of the original leapp tool that enables you to upgrade between CentOS systems
* or convert to RHEL using [convert2rhel](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/converting_from_an_rpm-based_linux_distribution_to_rhel/index) and then upgrade to RHEL 8 using [leapp ](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/upgrading_from_rhel_7_to_rhel_8/index)  (btw, not sure whether conversion from CentOS 8 Stream to RHEL is supported)

**Comment by j-mracek** [comment]
I am closing the issue because the system-upgrade will not help with the problem.
