### ISSUE TITLE
reboot and upgrade does not appear to work

### ISSUE THREAD

**Issue by pollend** [rpm-software-management/dnf-plugin-system-upgrade#9]
the reboot process will run startup load fedora and then just restart immediately after that. I'm pretty sure the reboot upgrade process did not quite work on my system.

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 121, in _main
    cli.check()
  File "/usr/lib/python2.7/site-packages/dnf/cli/cli.py", line 1036, in check
    self.command.doCheck(self.base.basecmd, self.base.extcmds)
  File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 251, in doCheck
    self._call_sub("check", basecmd, extcmds)
  File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 262, in _call_sub
    subfunc(*args)
  File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 323, in check_upgrade
    if os.readlink(MAGIC_SYMLINK) != self.state.datadir:
OSError: [Errno 2] No such file or directory: '/system-update'

it looks like the /system-update folder is never actually created.

**Comment by wgwoods** [comment]
Most likely it was deleted by PackageKit before we could get to it. This is a known problem which is fixed in PackageKit 1.0.8, which is available as an update for F22.

The next build of the `dnf-plugin-system-upgrade` RPM should have `Conflicts: PackageKit < 1.0.8`, which should ensure that other users won't hit this problem.

Please update to PackageKit 1.0.8 or higher and try again.
(or, if that's not possible: `systemctl mask packagekit-offline-update.service`) and try again.

**Comment by pollend** [comment]
are the fedora 23 repositories available. those repositories don't seem to be available after the upgrade.

**Comment by wgwoods** [comment]
They should be available, yes. Most of the updates for F23 are probably being held in `updates-testing` at the moment, though.

Since you said "after the upgrade", I'm assuming PK _was_ the problem, and you got the upgrade to work?

**Comment by pollend** [comment]
not really, I moved my files off and changed distributions. I might later just install the images from the fedora website given i'm on a clean slate now. sorry, didn't save any of the log files.
